### ISSUE TITLE
Added a file

### ISSUE THREAD

**Issue by gerryjackson** [steverpalmer/sandbox#3]
I received an email saying I was a subscriber to this repository that you seem to have set up as a test. I saw that I was given push access so I tried it and seem to have committed a source file. Hope you don't mind :)

**Comment by gerryjackson** [comment]
Oops, accidentally pressed Close, so re-opened it.

**Comment by steverpalmer** [comment]
Go for it.  I created this Sandbox to allow us to experiment with GitHub away from the important stuff.

Steve

On 20 November 2015 10:34:29 GMT+00:00, gerryjackson <notifications@github.com> wrote:
>I received an email saying I was a subscriber to this repository that
>you seem to have set up as a test. I saw that I was given push access
>so I tried it and seem to have committed a source file. Hope you don't
>mind :)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/steverpalmer/sandbox/issues/3

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by steverpalmer** [comment]
Tidy up
